name: Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Clean build folders
        run: |
          rmdir /s /q build || exit 0
          rmdir /s /q dist || exit 0
          rmdir /s /q spec || exit 0

      - name: Build app
        run: python build.py

      - name: Build installer
        run: python build1.py

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Multiaccount.exe
            dist/MultiaccountInstaller.exe