name: Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean build folders
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force spec -ErrorAction SilentlyContinue

      - name: Build app
        run: python build.py

      - name: Generate manifest
        run: python manifest.py ${{ github.ref_name }} ${{ github.repository }}
        
      - name: Build installer
        run: python build1.py

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Multiaccount.exe
            dist/MultiaccountInstaller.exe
            manifest.json
